# Generated by Django 5.2 on 2025-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=20)),
                ('tentativas', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
